from pyresparser import ResumeParser
# data = ResumeParser('sampo.pdf').get_extracted_data()
data = ResumeParser('sampo.pdf', skills_file='skills.csv').get_extracted_data()
print('\n')
print('Name: ', data['name'])
print('Email: ', data['email'])
print('Contact Number: ', data['mobile_number'])
# print('College Name: ', data['college_name'])
# print('Degree: ', data['degree'])
print('Skills: ', data['skills'])
# print('Company Name: ', data['company_names'])
# print('Designation: ', data['designation'])
# print('Total Experience: ', data['total_experience'])
print('Total number of Resume pages: ', data['no_of_pages'])
